# Cleaning Data with Pandas Exercises

For the exercises, you will be cleaning data in the Women's Clothing E-Commerce Reviews dataset.

To start cleaning data, we first need to create a dataframe from the CSV and print out any relevant info to make sure our dataframe is ready to go.

In [ ]:
# Import pandas and any other libraries you need here.
import pandas as pd
import numpy as np
# Create a new dataframe from your CSV
df = pd.read_csv('Womens Clothing E-Commerce Reviews.csv')

In [6]:
# Print out any information you need to understand your dataframe
df.head()

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               23486 non-null  int64
 1   Clothing ID              23486 non-null  int64
 2   Age                      23486 non-null  int64
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64
 6   Recommended IND          23486 non-null  int64
 7   Positive Feedback Count  23486 non-null  int64
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB

In [24]:
df.describe()

,Unnamed: 0,Clothing ID,Age,Rating,Recommended IND,Positive Feedback Count
count,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000,23486.000000
mean,11742.500000,918.118709,43.198544,4.196032,0.822362,2.535936
std,6779.968547,203.298980,12.279544,1.110031,0.382216,5.702202
min,0.000000,0.000000,18.000000,1.000000,0.000000,0.000000
25%,5871.250000,861.000000,34.000000,4.000000,1.000000,0.000000
50%,11742.500000,936.000000,41.000000,5.000000,1.000000,1.000000
75%,17613.750000,1078.000000,52.000000,5.000000,1.000000,3.000000
max,23485.000000,1205.000000,99.000000,5.000000,1.000000,122.000000

In [25]:
df.describe(include="object")

,Title,Review Text,Division Name,Department Name,Class Name
count,19676,22641,23472,23472,23472
unique,13993,22634,3,6,20
top,Love it!,Perfect fit and i've gotten so many compliment...,General,Tops,Dresses
freq,136,3,13850,10468,6319

In [27]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df.nunique() #seems like recommended IND should be a bool

Unnamed: 0                 23486
Clothing ID                 1206
Age                           77
Title                      13993
Review Text                22634
Rating                         5
Recommended IND                2
Positive Feedback Count       82
Division Name                  3
Department Name                6
Class Name                    20
dtype: int64

In [31]:
df["Rating"].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

np.int64(0)

In [72]:
df["Clothing ID"].duplicated().sum()

np.int64(22280)

In [38]:
df.sample(50)

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
7330,7330,1077,51,Love!!,I love this dress! i originally ordered it in...,5,1,0,General Petite,Dresses,Dresses
315,315,836,21,Beautiful top!,"Love this top! made with 100% cotton, a vintag...",5,1,8,General,Tops,Blouses
3487,3487,1056,26,Soft but fit oddly,"I wanted to love these, but the zipper is extr...",3,1,0,General Petite,Bottoms,Pants
20286,20286,828,61,Great purchase,I adore this top! the tencel fabric feels like...,5,1,3,General,Tops,Blouses
15681,15681,907,66,Gorgeous.,So lovely. perfect print / graphic. want to ...,5,1,0,General,Tops,Fine gauge
14048,14048,621,36,NaN,"Great dress, true to size....wore it to dinner...",5,1,0,General Petite,Intimate,Lounge
13697,13697,873,55,Sheer & lovely,"Tried both colors....gorgeous, but kept the wh...",4,1,1,General Petite,Tops,Knits
738,738,1137,66,Too cropped,"This runs small, i got the size 3 which fits l...",3,1,0,General,Trend,Trend
17139,17139,1205,34,Great fit,I'm normally a 12/14 and ordered my normal siz...,5,1,0,General,Bottoms,Pants
818,818,886,43,Not a great design,This shirt is not a good look for a gal with h...,2,0,0,General Petite,Tops,Knits
11707,11707,867,52,Cute top!,"This is exactly as pictured, and fits as it do...",4,1,1,General,Tops,Knits
15670,15670,865,70,"Love,love,love!!",I had originally bought this top in one of you...,5,1,0,General,Tops,Knits
10479,10479,873,42,Love this!,"Beautiful blouse, very flattering! if you run ...",5,1,0,General,Tops,Knits
3675,3675,547,38,Love this top!,This top is beautiful! it drapes just like the...,5,1,13,Initmates,Intimate,Layering
21516,21516,1060,59,Flattering!,The quality of the fabric and the design are p...,5,1,0,General,Bottoms,Pants
17872,17872,938,23,NaN,This tunic is amazing. i'm not usually one for...,5,1,1,General,Tops,Sweaters
6557,6557,1020,50,Perfect skirt,Thank you pilcro for making a skirt that is a ...,5,1,1,General,Bottoms,Skirts
16120,16120,862,43,Runs big,Runs really big. i usually wear small and this...,3,1,2,General,Tops,Knits
10791,10791,996,48,Ethereal and feminine.,Such a lovely skirt. i plan on wearing it to a...,5,1,0,General,Bottoms,Skirts
11192,11192,864,37,NaN,NaN,5,1,0,General,Tops,Knits
9590,9590,1081,49,Runs very small,"Beautiful dress, wonderful fabric, very well m...",3,1,0,General,Dresses,Dresses
22129,22129,872,83,Soooooooooooooo pretty!,I never buy prints.....but this was so underst...,5,1,4,General,Tops,Knits
21506,21506,855,43,Not for the petite,"I love the design and color of this cardigan, ...",3,1,6,General,Tops,Knits
21659,21659,1110,33,Love!,"Love love love this dress! but, if you are not...",5,1,0,General,Dresses,Dresses
9232,9232,1086,40,NaN,"I loved this dress, i usually wear a petite bu...",3,1,0,General,Dresses,Dresses
15397,15397,866,48,"Fabric seems cheaply made, very tight sleeves",I liked the colors and the design but it's kin...,3,0,5,General,Tops,Knits
22232,22232,1025,28,Love!,I've been trying to find a pair of tasteful de...,5,1,1,General Petite,Bottoms,Jeans
23057,23057,1035,32,Rip favorite pair,Lots of pairs of the pilcro serif-- and for so...,3,1,0,General,Bottoms,Jeans
22075,22075,850,46,Cute top. sizing not correct.,I just purchased this cute top at my local ret...,4,1,2,General,Tops,Blouses
21491,21491,854,49,NaN,I was immediately drawn to this tunic at the s...,5,1,0,General Petite,Tops,Knits
8491,8491,866,51,NaN,Love the shirt! the green is such a vibrant co...,4,1,0,General,Tops,Knits
9965,9965,1080,34,Foiled once again by my petite-ness,I ordered this in a small petite. with tracy r...,3,1,2,General,Dresses,Dresses
4316,4316,1078,46,Extremely awkward,I bought this online so didn't realize that th...,1,0,9,General,Dresses,Dresses
22388,22388,1094,55,Pretty but big,This dress is really pretty and fun. i can see...,4,1,8,General,Dresses,Dresses
11568,11568,667,45,Cute two way top!,This top is adorable. i love it! i couldn't fi...,4,1,0,General Petite,Intimate,Lounge
22972,22972,1107,47,Beautiful knit dress - runs way large!,I ordered an xxs petite and this hangs like a ...,2,0,27,General Petite,Dresses,Dresses
15091,15091,872,46,NaN,I bought this top in white. i wore it with bla...,5,1,14,General,Tops,Knits
4867,4867,834,45,So cute!,I am in love with this top. it is so feminine ...,5,1,14,General Petite,Tops,Blouses
15212,15212,1033,40,Flattering cut,Really like these -- they fit really well and ...,5,1,3,General Petite,Bottoms,Jeans
13976,13976,828,46,NaN,Beautiful pattern and shape! however i had to ...,3,0,4,General,Tops,Blouses
15801,15801,1092,47,Returned for another size,Great comfortable dress with style! this ran a...,5,1,0,General Petite,Dresses,Dresses
13472,13472,1125,49,Buttons have not been fixed despite retailer's...,"Despite retailer's claim that they have ""fixed...",2,0,4,General Petite,Jackets,Outerwear
5058,5058,1095,48,Lovely pattern,"I really wanted to like this dress, but it jus...",4,1,2,General Petite,Dresses,Dresses
2938,2938,995,35,NaN,NaN,3,0,0,General,Bottoms,Skirts
1627,1627,1059,47,Adorable,These pants are so fun. i love the pattern and...,4,1,1,General,Bottoms,Pants
11420,11420,1022,35,Runs small!,These cuff jeans are very good looking! 4 star...,4,1,9,General,Bottoms,Jeans
7372,7372,820,39,Second time's the cahrm,"I tried this one twice, in the same day, the f...",5,1,15,General Petite,Tops,Blouses
9272,9272,1086,60,"Omg, perfect dress!",Love this dress! very soft and easy to wear. i...,5,1,0,General,Dresses,Dresses
4664,4664,1048,47,A very nice surprise,I think i've made a hobby out of trying on jum...,5,1,5,General Petite,Bottoms,Pants
12476,12476,605,33,NaN,"The are so comfortable, flattering, and i feel...",5,1,0,General,Bottoms,Shorts

In [17]:
df["Title"].value_counts(dropna=False)

Title
NaN                                    3810
Love it!                                136
Beautiful                                95
Love                                     88
Love!                                    84
                                       ...
Full skirt                                1
Not exactly what i expected               1
Flattering and lovely sweater dress       1
Perfect except slip                       1
Cagrcoal shimmer fun                      1
Name: count, Length: 13994, dtype: int64

In [18]:
df.value_counts("Rating")

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

In [68]:
df.value_counts(dropna=False)

Unnamed: 0  Clothing ID  Age  Title                                               Review Text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Rating  Recommended IND  Positive Feedback Count  Division Name   Department Name  Class Name
0           767          33   NaN                                                 Absolutely wonderful - silky and sexy and comfortable                                                                                                                                                                                                                                                                                                                                                                                                                                                                 4       1                0                        Initmates       Intimate         Intimates     1
1           1080         34   NaN                                                 Love this dress!  it's sooo pretty.  i happened to find it in a store, and i'm glad i did bc i never would have ordered it online bc it's petite.  i bought a petite and am 5'8".  i love the length on me- hits just a little below the knee.  would definitely be a true midi on someone who is truly petite.                                                                                                                                                                                                       5       1                4                        General         Dresses          Dresses       1
2           1077         60   Some major design flaws                             I had such high hopes for this dress and really wanted it to work for me. i initially ordered the petite small (my usual size) but i found this to be outrageously small. so small in fact that i could not zip it up! i reordered it in petite medium, which was just ok. overall, the top half was comfortable and fit nicely, but the bottom half had a very tight under layer and several somewhat cheap (net) over layers. imo, a major design flaw was the net over layer sewn directly into the zipper - it c  3       0                0                        General         Dresses          Dresses       1
3           1049         50   My favorite buy!                                    I love, love, love this jumpsuit. it's fun, flirty, and fabulous! every time i wear it, i get nothing but great compliments!                                                                                                                                                                                                                                                                                                                                                                                          5       1                0                        General Petite  Bottoms          Pants         1
4           847          47   Flattering shirt                                    This shirt is very flattering to all due to the adjustable front tie. it is the perfect length to wear with leggings and it is sleeveless so it pairs well with any cardigan. love this shirt!!!                                                                                                                                                                                                                                                                                                                      5       1                6                        General         Tops             Blouses       1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ..
23481       1104         34   Great dress for many occasions                      I was very happy to snag this dress at such a great price! it's very easy to slip on and has a very flattering cut and color combo.                                                                                                                                                                                                                                                                                                                                                                                   5       1                0                        General Petite  Dresses          Dresses       1
23482       862          48   Wish it was made of cotton                          It reminds me of maternity clothes. soft, stretchy, shiny material. cut is flattering and drapes nicely. i only found one button to close front... looked awkward. nice long sleeves.\nnot for me but maybe for others. just ok.                                                                                                                                                                                                                                                                                      3       1                0                        General Petite  Tops             Knits         1
23483       1104         31   Cute, but see through                               This fit well, but the top was very see through. this never would have worked for me. i'm glad i was able to try it on in the store and didn't order it online. with different fabric, it would have been great.                                                                                                                                                                                                                                                                                                      3       0                1                        General Petite  Dresses          Dresses       1
23484       1084         28   Very cute dress, perfect for summer parties and we  I bought this dress for a wedding i have this summer, and it's so cute. unfortunately the fit isn't perfect. the medium fits my waist perfectly, but was way too long and too big in the bust and shoulders. if i wanted to spend the money, i could get it tailored, but i just felt like it might not be worth it. side note - this dress was delivered to me with a nordstrom tag on it and i found it much cheaper there after looking!                                                                           3       1                2                        General         Dresses          Dresses       1
23485       1104         52   Please make more like this one!                     This dress in a lovely platinum is feminine and fits perfectly, easy to wear and comfy, too! highly recommend!                                                                                                                                                                                                                                                                                                                                                                                                        5       1                22                       General Petite  Dresses          Dresses       1
Name: count, Length: 23486, dtype: int64

## Missing Data

Try out different methods to locate and resolve missing data.

In [51]:
# Try to find some missing data!
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [62]:
missing_rows = df[df.isna().any(axis=1)]
missing_rows.head(25)

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
11,11,1095,39,NaN,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses
30,30,1060,33,NaN,Beautifully made pants and on trend with the f...,5,1,0,General Petite,Bottoms,Pants
36,36,1002,29,NaN,This is a comfortable skirt that can span seas...,4,1,5,General,Bottoms,Skirts
38,38,684,36,NaN,Super cute and comfy pull over. sizing is accu...,5,1,2,Initmates,Intimate,Lounge
39,39,862,59,NaN,Great casual top with flare. looks cute with g...,5,1,0,General,Tops,Knits
40,40,862,47,NaN,Pretty and unique. great with jeans or i have ...,4,1,1,General,Tops,Knits
41,41,862,40,NaN,This is a beautiful top. it's unique and not s...,5,1,0,General,Tops,Knits
46,46,862,40,NaN,I love this top. i wear it all the time. the ...,5,1,0,General,Tops,Knits
47,47,823,52,NaN,"Very comfortable, material is good, cut out on...",5,1,0,General,Tops,Blouses
52,52,1104,39,NaN,"Love the color and style, but material snags e...",3,1,3,General,Dresses,Dresses
56,56,368,33,NaN,I am pregnant and i thought this would be a gr...,2,0,3,Initmates,Intimate,Intimates
58,58,1095,36,NaN,"I got this in the petite length, size o, and i...",4,1,0,General Petite,Dresses,Dresses
65,65,862,58,NaN,"Beautiful top, but delicate! i wore it to scho...",4,1,2,General,Tops,Knits
73,73,866,47,NaN,I love this top. it is loose and comfortable. ...,4,1,0,General Petite,Tops,Knits
74,74,1081,59,NaN,I passed up this dress so many times in the st...,5,1,1,General Petite,Dresses,Dresses
81,81,863,61,NaN,Loved this top. great design. comfortable and ...,5,1,4,General Petite,Tops,Knits
85,85,866,58,NaN,"I was really hoping to like this, but it did n...",1,0,2,General Petite,Tops,Knits
91,91,850,29,NaN,This top is so much prettier in real life than...,5,1,5,General Petite,Tops,Blouses
92,92,861,23,NaN,NaN,5,1,0,General Petite,Tops,Knits
93,93,1081,31,NaN,NaN,5,1,0,General,Dresses,Dresses
96,96,845,44,NaN,I usually wear a medium and bought a small. it...,1,0,0,General Petite,Tops,Blouses
98,98,1133,50,NaN,NaN,5,1,0,General,Jackets,Outerwear
104,104,863,51,NaN,"Runs big and looked unflattering. i am petite,...",2,0,0,General,Tops,Knits

In [65]:
(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

Title                      16.222430
Review Text                 3.597888
Department Name             0.059610
Class Name                  0.059610
Division Name               0.059610
Unnamed: 0                  0.000000
Clothing ID                 0.000000
Age                         0.000000
Rating                      0.000000
Recommended IND             0.000000
Positive Feedback Count     0.000000
dtype: float64

In [58]:
df["Recommended IND"].isnull().value_counts()

Recommended IND
False    23486
Name: count, dtype: int64

In [61]:
df["Title"].unique()

array([nan, 'Some major design flaws', 'My favorite buy!', ...,
       'Cute, but see through',
       'Very cute dress, perfect for summer parties and we',
       'Please make more like this one!'], shape=(13994,), dtype=object)

In [73]:
missing_strings = ["N/A", "n/a", "NA", "", '"N/A"', '"n/a"', '"NA"']
mask = df.isin(missing_strings)
mask.sum()

Unnamed: 0                 0
Clothing ID                0
Age                        0
Title                      0
Review Text                0
Rating                     0
Recommended IND            0
Positive Feedback Count    0
Division Name              0
Department Name            0
Class Name                 0
dtype: int64

Did you find any missing data? What things worked well for you and what did not?

In [ ]:
# Respond to the above questions here:
# Yes, the Title collumn has the most missing data. Next is review text. The rest of the missing data seems miniscule and should be easy to handle. Getting the percentage of 
# missing data in each collumn was a good frame of reference. The unique values weren't super useful, except for maybe the Recommended IND collumn should maybe be a bool data type since 
# all the values are equal to 1 or 0.

## Irregular Data

With missing data out of the way, turn your attention to any outliers. Just as we did for missing data, we first need to detect the outliers.

In [74]:
# Keep an eye out for outliers!
df["Rating"].describe()

count    23486.000000
mean         4.196032
std          1.110031
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: Rating, dtype: float64

In [75]:
df["Clothing ID"].describe()

count    23486.000000
mean       918.118709
std        203.298980
min          0.000000
25%        861.000000
50%        936.000000
75%       1078.000000
max       1205.000000
Name: Clothing ID, dtype: float64

In [77]:
df["Title"].describe()

count        19676
unique       13993
top       Love it!
freq           136
Name: Title, dtype: object

What techniques helped you find outliers? In your opinion, what about the techniques you used made them effective?

In [ ]:
# Make your notes here: I used .describe() to check min, max, and quartiles, which quickly highlighted unusually high or low values as potential outliers.

## Unnecessary Data

Unnecessary data could be irrelevant to your analysis or a duplice column. Check out the dataset to see if there is any unnecessary data.

In [80]:
# Look out for unnecessary data!
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [83]:
df = df.drop(columns=["Unnamed: 0"])

KeyError: "['Unnamed: 0'] not found in axis"

In [94]:
df.head(25)

,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
0,767,33,NaN,Absolutely wonderful - silky and sexy and comf...,4,1,0,Initmates,Intimate,Intimates
1,1080,34,NaN,Love this dress! it's sooo pretty. i happene...,5,1,4,General,Dresses,Dresses
2,1077,60,Some major design flaws,I had such high hopes for this dress and reall...,3,0,0,General,Dresses,Dresses
3,1049,50,My favorite buy!,"I love, love, love this jumpsuit. it's fun, fl...",5,1,0,General Petite,Bottoms,Pants
4,847,47,Flattering shirt,This shirt is very flattering to all due to th...,5,1,6,General,Tops,Blouses
5,1080,49,Not for the very petite,"I love tracy reese dresses, but this one is no...",2,0,4,General,Dresses,Dresses
6,858,39,Cagrcoal shimmer fun,I aded this in my basket at hte last mintue to...,5,1,1,General Petite,Tops,Knits
7,858,39,"Shimmer, surprisingly goes with lots","I ordered this in carbon for store pick up, an...",4,1,4,General Petite,Tops,Knits
8,1077,24,Flattering,I love this dress. i usually get an xs but it ...,5,1,0,General,Dresses,Dresses
9,1077,34,Such a fun dress!,"I'm 5""5' and 125 lbs. i ordered the s petite t...",5,1,0,General,Dresses,Dresses
10,1077,53,Dress looks like it's made of cheap material,Dress runs small esp where the zipper area run...,3,0,14,General,Dresses,Dresses
11,1095,39,NaN,This dress is perfection! so pretty and flatte...,5,1,2,General Petite,Dresses,Dresses
12,1095,53,Perfect!!!,More and more i find myself reliant on the rev...,5,1,2,General Petite,Dresses,Dresses
13,767,44,Runs big,Bought the black xs to go under the larkspur m...,5,1,0,Initmates,Intimate,Intimates
14,1077,50,Pretty party dress with some issues,This is a nice choice for holiday gatherings. ...,3,1,1,General,Dresses,Dresses
15,1065,47,"Nice, but not for my body",I took these out of the package and wanted the...,4,1,3,General,Bottoms,Pants
16,1065,34,"You need to be at least average height, or taller",Material and color is nice. the leg opening i...,3,1,2,General,Bottoms,Pants
17,853,41,Looks great with white pants,Took a chance on this blouse and so glad i did...,5,1,0,General,Tops,Blouses
18,1120,32,Super cute and cozy,"A flattering, super cozy coat. will work well...",5,1,0,General,Jackets,Outerwear
19,1077,47,Stylish and comfortable,I love the look and feel of this tulle dress. ...,5,1,0,General,Dresses,Dresses
20,847,33,"Cute, crisp shirt","If this product was in petite, i would get the...",4,1,2,General,Tops,Blouses
21,1080,55,I'm torn!,"I'm upset because for the price of the dress, ...",4,1,14,General,Dresses,Dresses
22,1077,31,Not what it looks like,"First of all, this is not pullover styling. th...",2,0,7,General,Dresses,Dresses
23,1077,34,"Like it, but don't love it.",Cute little dress fits tts. it is a little hig...,3,1,0,General,Dresses,Dresses
24,847,55,Versatile,"I love this shirt because when i first saw it,...",5,1,0,General,Tops,Blouses

In [96]:
df["Age"].describe()

count    23486.000000
mean        43.198544
std         12.279544
min         18.000000
25%         34.000000
50%         41.000000
75%         52.000000
max         99.000000
Name: Age, dtype: float64

In [97]:
df["Rating"].describe()

count    23486.000000
mean         4.196032
std          1.110031
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: Rating, dtype: float64

Did you find any unnecessary data in your dataset? How did you handle it?

In [ ]:
# Make your notes here. 
# yes there was an unamed column that was a duplice. I dropped that column. The rest of the data seemed valid.

## Inconsistent Data

Inconsistent data is likely due to inconsistent formatting and can be addressed by re-formatting all values in a column or row.

In [109]:
# Look out for inconsistent data!
df["Division Name"].unique()

array(['Initmates', 'General', 'General Petite', nan], dtype=object)

In [110]:
df["Department Name"].unique()

array(['Intimate', 'Dresses', 'Bottoms', 'Tops', 'Jackets', 'Trend', nan],
      dtype=object)

In [121]:
df["Class Name"].unique()

array(['Intimates', 'Dresses', 'Pants', 'Blouses', 'Knits', 'Outerwear',
       'Lounge', 'Sweaters', 'Skirts', 'Fine gauge', 'Sleep', 'Jackets',
       'Swim', 'Trend', 'Jeans', 'Legwear', 'Shorts', 'Layering',
       'Casual bottoms', nan, 'Chemises'], dtype=object)

In [128]:
df["Class Name"].value_counts()

Class Name
Dresses       6319
Knits         4843
Blouses       3097
Sweaters      1428
Pants         1390
Jeans         1147
Fine Gauge    1100
Skirts         945
Jackets        704
Lounge         691
Swim           350
Outerwear      328
Shorts         317
Sleep          229
Legwear        165
Intimates      154
Layering       146
Trend          119
Name: count, dtype: int64

Did you find any inconsistent data? What did you do to clean it?

In [ ]:
# Make your notes here!
# Yes, found a typo in one of the categories, there are very similar and redundant class names, including two that only contain 1 and 2 values (casual botoms).

In [ ]:
df["Division Name"] = df["Division Name"].replace("Initmates", "Intimates") # fixed typo in "intimates"

In [ ]:
df["Division Name"] = df["Division Name"].str.title()
df["Department Name"] = df["Department Name"].str.title()
df["Class Name"] = df["Class Name"].str.title()

# standardized capitalization formatting

In [127]:
df["Class Name"] = df["Class Name"].replace({"Casual Bottoms": "Pants", "Chemises": "Sleep"})

# merged unecessary catagories.